// <auto-generated />
using System;
using HubClub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HubClub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260710155643_AddMySqlConcurrency")]
    partial class AddMySqlConcurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HubClub.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.HasKey("CustomerId");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("HubClub.Models.DailyClosing", b =>
                {
                    b.Property<int>("ClosingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClosingId"));

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date");

                    b.Property<string>("ExcelBackupPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalCash")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalProductRevenue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalTimeRevenue")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ClosingId");

                    b.ToTable("daily_closings");
                });

            modelBuilder.Entity("HubClub.Models.Package", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PackageId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("NumberOfHours")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PackageId");

                    b.ToTable("packages");
                });

            modelBuilder.Entity("HubClub.Models.PricingSetting", b =>
                {
                    b.Property<int>("PricingSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PricingSettingId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MaxNumberOfHours")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("MinNumberOfHours")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PricingSettingId");

                    b.ToTable("pricing_settings");
                });

            modelBuilder.Entity("HubClub.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("ProductId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("HubClub.Models.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date");

                    b.Property<int>("CusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<int?>("PriceSettingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalProductPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalTimePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("UserPackageId")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.HasIndex("CusId");

                    b.HasIndex("PriceSettingId");

                    b.HasIndex("UserPackageId");

                    b.ToTable("sessions");
                });

            modelBuilder.Entity("HubClub.Models.SessionProduct", b =>
                {
                    b.Property<int>("SProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SProductId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPriceAtSale")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SProductId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SessionId");

                    b.ToTable("session_products");
                });

            modelBuilder.Entity("HubClub.Models.StockMovement", b =>
                {
                    b.Property<int>("StockMovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StockMovementId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityChanged")
                        .HasColumnType("int");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("StockMovementId");

                    b.HasIndex("ProductId");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("HubClub.Models.UserPackage", b =>
                {
                    b.Property<int>("UserPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserPackageId"));

                    b.Property<int>("CusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("RemainingHours")
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("UserPackageId");

                    b.HasIndex("CusId");

                    b.HasIndex("PackageId");

                    b.ToTable("user_packages");
                });

            modelBuilder.Entity("HubClub.Models.Session", b =>
                {
                    b.HasOne("HubClub.Models.Customer", "Customer")
                        .WithMany("Sessions")
                        .HasForeignKey("CusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HubClub.Models.PricingSetting", "PricingSetting")
                        .WithMany("Sessions")
                        .HasForeignKey("PriceSettingId");

                    b.HasOne("HubClub.Models.UserPackage", "UserPackage")
                        .WithMany("Sessions")
                        .HasForeignKey("UserPackageId");

                    b.Navigation("Customer");

                    b.Navigation("PricingSetting");

                    b.Navigation("UserPackage");
                });

            modelBuilder.Entity("HubClub.Models.SessionProduct", b =>
                {
                    b.HasOne("HubClub.Models.Product", "Product")
                        .WithMany("SessionProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HubClub.Models.Session", "Session")
                        .WithMany("SessionProducts")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("HubClub.Models.StockMovement", b =>
                {
                    b.HasOne("HubClub.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HubClub.Models.UserPackage", b =>
                {
                    b.HasOne("HubClub.Models.Customer", "Customer")
                        .WithMany("UserPackages")
                        .HasForeignKey("CusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HubClub.Models.Package", "Package")
                        .WithMany("UserPackages")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("HubClub.Models.Customer", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("UserPackages");
                });

            modelBuilder.Entity("HubClub.Models.Package", b =>
                {
                    b.Navigation("UserPackages");
                });

            modelBuilder.Entity("HubClub.Models.PricingSetting", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("HubClub.Models.Product", b =>
                {
                    b.Navigation("SessionProducts");
                });

            modelBuilder.Entity("HubClub.Models.Session", b =>
                {
                    b.Navigation("SessionProducts");
                });

            modelBuilder.Entity("HubClub.Models.UserPackage", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
